# Generated by Django 4.2.27 on 2025-12-25 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coffeemood',
            options={'ordering': ['-created_at'], 'verbose_name': 'درخواست پیشنهاد قهوه', 'verbose_name_plural': 'درخواست\u200cهای پیشنهاد قهوه'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'آیتم منو', 'verbose_name_plural': 'آیتم\u200cهای منو'},
        ),
        migrations.AlterField(
            model_name='coffeemood',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='coffeemood',
            name='description',
            field=models.CharField(max_length=255, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='coffeemood',
            name='last_coffee',
            field=models.CharField(max_length=50, verbose_name='آخرین قهوه'),
        ),
        migrations.AlterField(
            model_name='coffeemood',
            name='mood',
            field=models.CharField(max_length=50, verbose_name='حال و احوال'),
        ),
        migrations.AlterField(
            model_name='coffeemood',
            name='taste',
            field=models.CharField(max_length=50, verbose_name='ذائقه'),
        ),
        migrations.AlterField(
            model_name='coffeemood',
            name='time_of_day',
            field=models.CharField(max_length=50, verbose_name='زمان روز'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='image',
            field=models.ImageField(upload_to='menu/', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item',
            field=models.CharField(max_length=255, verbose_name='نام آیتم'),
        ),
    ]
